# Generated by Django 4.1.7 on 2023-04-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='preco',
            new_name='valor',
        ),
    ]
