# Generated by Django 4.1.7 on 2023-04-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_rename_preco_book_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='endereço',
        ),
    ]
