# Generated by Django 4.1.7 on 2023-04-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_rename_endereco_cliente_endereço'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Livro',
        ),
    ]
