# Generated by Django 4.1.7 on 2023-04-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_rename_book_livro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Escritor',
        ),
    ]
